name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm ci

      - run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install -g npm-registry-fetch

      - run: npx npm-registry-fetch publish --access public

  create-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Create Changelog
        uses: actions/create-release-notes@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-range: ${{ github.event.after }}...${{ github.event.before }}
          version-format: "v%s"

  write-release-notes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Write release notes
        run: |
          echo "### Release notes"
          cat CHANGELOG.md

  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-release@v2
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: ${{ github.event.release.name }}
        body: ${{ steps.Write-release-notes.outputs.release-notes }}
