name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 20

      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies and build the project
        run: npm install && npm run build
  
  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 20

      - uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Npm Package Publish
        run: npm publish