name: Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16

  #     - name: Install dependencies and build the project
  #       run: npm install && npm run build

  release:
    # needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get the version from package.json
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Read Changelog
        id: read_changelog
        run: |
          changelog=$(awk '/^#/ {f++} f == 1 && f++ {print} f == 2 {exit}' CHANGELOG.md)
          echo "::set-output name=changelog::$changelog"
        shell: bash

      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: v${{ env.VERSION }}
          body: |
            ${{ steps.read_changelog.outputs.changelog }}
          draft: false
          prerelease: false